# EX-1(Matrix Multiplication)

In [3]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.dot(A,B)
print("matrix A:",A)
print("matrix B:",B)
print("Matrix C(A*B):",C)

matrix A: [[1 2]
 [3 4]]
matrix B: [[5 6]
 [7 8]]
Matrix C(A*B): [[19 22]
 [43 50]]


# EX-2(Eigen Decomposition)

In [4]:
import numpy as np
A=np.array([[4,2],[1,3]])
eigenvalue,eigenvectors=np.linalg.eig(A)
print("Matrix A:",A)
print("Eigen Values:",eigenvalue)
print("Eigen vectors:",eigenvectors)

Matrix A: [[4 2]
 [1 3]]
Eigen Values: [5. 2.]
Eigen vectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# EX-3(SVD)

In [5]:
import numpy as np
A=np.array([[3,2,2],[2,3,-2]])
U,S,V=np.linalg.svd(A)
print("matrix A:\n",A)
print("U matrix:\n",U)
print("Singular values:\n",S)
print("V matrix:\n",V)

matrix A:
 [[ 3  2  2]
 [ 2  3 -2]]
U matrix:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Singular values:
 [5. 3.]
V matrix:
 [[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


# EX-4(Determinant calculation)

In [6]:
import numpy as np
A=np.array([[6,1],[2,3]])
det=np.linalg.det(A)
print("matrix A:\n",A)
print("Determinant of A:\n",det)

matrix A:
 [[6 1]
 [2 3]]
Determinant of A:
 15.999999999999998


# EX-5(Norm Calculation) 

In [7]:
import numpy as np
V=np.array([3,4])
L1_norm=np.linalg.norm(V,ord=1)
L2_norm=np.linalg.norm(V)
print("vector V:\n",V)
print("L1 norm of V:\n",L1_norm)
print("L2 norm of V:\n",L2_norm)

vector V:
 [3 4]
L1 norm of V:
 7.0
L2 norm of V:
 5.0
